# Generated by Django 5.0.6 on 2024-06-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
